version: '3'
services:
  web:
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    links:
      - "db:test"
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test

    ports:
      - "3306:3306"